=== mobadri/chat-client/chat-bot/chat_bot_keys.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="keys" type="keysType"/>
  <xs:complexType name="valueType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="weight" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="valuesType">
    <xs:sequence>
      <xs:element type="valueType" name="value" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="keyType">
    <xs:sequence>
      <xs:element type="valuesType" name="values"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="keysType">
    <xs:sequence>
      <xs:element type="keyType" name="key" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== mobadri/chat-client/chat-bot/01145785655.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat_bot_keys.xsd">
    
 
 
 <key name="hello">
        
  
  
  <values>
            
   
   
   <value weight="1">hi</value>
           
  
  
  </values>
       
 
 
 </key>
   
 
 
 <key name="hiiiiiiiiiiiiiiiiiiiii">
      
  
  <values>
         
   
   <value weight="3">hellllllllllllllllllllo</value>
        
  
  </values>
     
 
 </key>
  
 
 <key name="heeeeeeeee">
    
  <values>
      
   <value weight="1">helllo</value>
     
  </values>
   
 </key>
 
 <key name="sdjnijrg">
  <values>
   <value weight="1">fdfrnrtbsba</value>
  </values>
 </key>
</keys>

=== mobadri/chat-client/chat-bot/chat_bot_keys.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat_bot_keys.xsd">

    <key name="welcome">

        <values>

            <value weight="1">hello</value>

            <value weight="1">hala wllah</value>

        <value weight="1">hala</value><value weight="5">welcome</value></values>

    </key>

    <key name="hi">

        <values>

            <value weight="3">hello</value>

            <value weight="1">yahala</value>
        <value weight="2">welcome</value><value weight="1">hala be 4bab</value></values>

    </key>
</keys>

=== mobadri/chat-client/chat-bot/01145785651.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat_bot_keys.xsd">
   
 
 <key name="hellllllllllllllllllllo">
      
  
  <values>
         
   
   <value weight="2">hiiiiiiiiiiiiiiiiiiiii</value>
        
  
  </values>
     
 
 </key>
  
 
 <key name="helllo">
    
  <values>
      
   <value weight="1">heeeeeeeee</value>
     
  </values>
   
 </key>
 
 <key name="dfshrgb">
  <values>
   <value weight="1">sfdhrgb</value>
  </values>
 </key>
</keys>

=== mobadri/chat-client/chat-bot/01111263130.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat_bot_keys.xsd">
     
 <key name="welcome">
          
  <values>
               
   <value weight="1">hello</value>
               
   <value weight="1">hala wllah</value>
               
   <value weight="1">hala</value>
               
   <value weight="5">welcome</value>
           
  </values>
      
 </key>
     
 <key name="hi">
          
  <values>
               
   <value weight="3">hello</value>
               
   <value weight="1">yahala</value>
               
   <value weight="2">welcome</value>
               
   <value weight="1">hala be 4bab</value>
           
  </values>
      
 </key>
     
 <key name="ya hala be shbab">
          
  <values>
               
   <value weight="1">hello</value>
           
  </values>
      
 </key>
     
 <key name="hala feek">
          
  <values>
               
   <value weight="1">hala w 8ala</value>
           
  </values>
      
 </key>
     
 <key name="hello">
          
  <values>
               
   <value weight="1">welcome ya welcome</value>
           
  </values>
      
 </key>
     
 <key name="your name ?">
          
  <values>
               
   <value weight="1">noura</value>
           
  </values>
      
 </key>
     
 <key name="hellooz">
          
  <values>
               
   <value weight="1">ya 5bar</value>
           
  </values>
      
 </key>
 
 <key name="ya hala w 8ala">
  <values>
   <value weight="1">msm</value>
  </values>
 </key>
 <key name="zy el fol">
  <values>
   <value weight="1">ana tmam w ent ?</value>
   <value weight="1">ya gd3</value>
  </values>
 </key>
 <key name="mazaaa">
  <values>
   <value weight="1">wla 6aga</value>
  </values>
 </key>
</keys>
